-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQw2MGlU9g9z3WwmX
ptAjbb4dh1+cO7Tr8P+IYybJzfSgCgYIKoZIzj0DAQehRANCAASMgIV1WNKhOnTk
aKwA0oTQerhs1ZJb/jhu/hgTHyAnn5B5MYFHM3/kFOq2HNAMBPS1H6oPNnvAaMKY
GL7+O6s+
-----END PRIVATE KEY-----